version: "3"

services:
  emailservice:
    build: EmailService
    ports:
      - 8000:8000
    environment:
      VIRTUAL_HOST: localhost

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true
