version: "3"

services:
  emailservice:
    build: EmailService
    ports:
      - 8000:8000
    environment:
      VIRTUAL_HOST: localhost

  reverse-proxy:
    build: nginx
    depends_on: [emailservice]
    ports:
      - 80:80
      - 443:443

    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_PROXY_CONTAINER: "reverse-proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
