version: "3"

services:
  emailservice:
    build: EmailService
    ports:
      - 8000:8000
    environment:
      VIRTUAL_HOST: localhost

  reverse-proxy:
    build: nginx
    depends_on: [emailservice]
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
