FROM node:12-alpine
COPY ./package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.15
COPY --from=build-stage /build/ /usr/share/nginx/html
COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf